eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
  application:
    name: auth-center