server:
  port: 8081
  # localhost:8081
  # 运行后可以进入eureka管理页

eureka:
  instance:
    hostname: eureka-serve
  client:
    # 单机版Eureka Server
    register-with-eureka: false  #表识不向注册中心注册自己
    fetch-registry: false        #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
