spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shirodb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai"
    username: root
    password:


pagehelper:
  helper-dialect: mysql
  reasonable: true

server:
  port: 8086